### ISSUE TITLE
Some rotations yield non-unitaries

### ISSUE THREAD

**Issue by NUrgell** [quantumdilley/SO-3-to-SU-2-#2]
Hi,
I have been testing the Mathematica and Python version of the code and realized that certain rotations yield non-unitary matrices.

As an example, the matrix $Rot=[[-2.39059004e^{-01}, -9.71005043e^{-01}, 0], [0, 0,-1.46544109e-02+9.99892618e-01j], [ 1.42295069e^{-02}-9.70900775e^{-01}j ,-3.50326887e^{-03}+2.39033333e^{-01}j, 0]]$ yields the non-unitary matrix $U=[[ 0.43615966-0.55656514j -0.42795669-0.56289703j],[-0.44426896+0.55011371j  0.43615966+0.55656514j]]$ which yields $UU^\dagger=[[ 1. ,  -0.99989262],[-0.99989262,  1. ]]\neq \mathbb{1}$ . I had similar issues with the mathematica code. Have you encountered similar issues? Did you find a solution to this problem?

Thank you!

(Edit: The issue possibly arises from the determinant of the rotation matrix not being close enough to 1)

**Comment by quantumdilley** [comment]
Hello NUrgell,
I used your correlation matrix, {{-0.207591, 0.978216, 0.}, {0.978216, 0.207591, 0.}, {0., 0., -1.}},  in the definition so2su and got the unitary matrix {{0, -0.777043 - 0.629448 I}, {0.777043 - 0.629448 I, 0}}. It looks like you were getting the zero matrix as a solution. Which function were you using to obtain the unitary?
Best,Daniel Dilley
    On Tuesday, March 19, 2024 at 03:06:02 AM CDT, NUrgell ***@***.***> wrote:  
 
 


Hi,
I have been testing the Mathematica version of the code and realized that certain SO(3) matrices yield non-unitary matrices.
As an example, the matrix {{-0.207591, 0.978216, 0.}, {0.978216, 0.207591, 0.}, {0., 0., -1.}} yields the non unitary matrix {{1.0536710^-8 + 0. I, 0. + 0. I}, {0. + 0. I, 1.0536710^-8 + 0. I}}. I have been able to compute the correct SU(2) matrix which is {{0, -0.777043 + 0.629448 I}, {0.777043 + 0.629448 I, 0}}. I have encountered the same issue with the Python version of the code. Have you encountered similar issues? Did you find a solution to this problem?

Thank you!

**Comment by NUrgell** [comment]
Hi Daniel,

I haven't been able to locate the exact code I was using previously, but I'm now obtaining the correct results with the updated version of Mathematica I currently have. Regarding the issues I encountered with the Python implementation of the code, I discovered a bug in a sympy function I was utilizing, so the problem wasn't related to your function, and the errors have been rectified.

Thank you for your assistance, and please accept my apologies for any inconvenience I may have caused.

Best regards,
Núria

**Comment by quantumdilley** [comment]
Hello Núria,
No worries! I'm glad everything is working now. Thanks for checking the work.
Best,Daniel Dilley
    On Tuesday, March 19, 2024 at 08:11:26 AM CDT, NUrgell ***@***.***> wrote:  
 
 


Hi Daniel,

I haven't been able to locate the exact code I was using previously, but I'm now obtaining the correct results with the updated version of Mathematica I currently have. Regarding the issues I encountered with the Python implementation of the code, I discovered a bug in a sympy function I was utilizing, so the problem wasn't related to your function, and the errors have been rectified.

Thank you for your assistance, and please accept my apologies for any inconvenience I may have caused.

Best regards,
Núria
